### ISSUE TITLE
create UI for adding/editing options for select like sector, team, offer V2

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-web#40]
- now some options for the selects are taken from the API http://167.71.48.30:5000/api/tag/<key> , where key could be sector, team, offer etc
- we need a section like users/volunteer/benficary to add/edit the tags with list/column and filter, add new tag and edit on click item
item format:
```
{
      "_id": "5e8e128196a3ab0290c96607", 
      "en": "-", 
      "is_active": true, 
      "ro": "Balti", 
      "ru": "-", 
      "select": "sector"
    }
```
-  need just `ro` property for now
- need filter by is_active, select filter
- need list with is_active, select and ro column - get method to api/tag
- need add new tag with: select[team, offer, sector] options, ro field, is_active - boolean - post method to /api/tag
- need edit tag with same field like new tag - put method to api/tag

**Comment by johnsmithm** [comment]
version 2

**Comment by unrevised6419** [comment]
Was decided to remove tags
