### ISSUE TITLE
add posters on welcome component

### ISSUE THREAD

**Issue by grigore-fiodorov** [code4moldova/voluntar-web#60]
- [ ] after #59 
- [ ] get posters [from](https://drive.google.com/drive/folders/1AQXjjVv3uaSkeiRKvLN3nQpaHRE7TA9B?fbclid=IwAR2Hoyj86n2pIHe8JDkO1PAEfQIJbsgRM7MsNscfxj2Dyq0FZWbIB0La2xU)
- [ ] show only "linia verde" image format and download pdf format
- [ ] implement
smth like that:
![image](https://user-images.githubusercontent.com/16736593/79049161-76b0f280-7c2a-11ea-877a-e27aa1b98773.png)

**Comment by mihaelataranu7** [comment]
need to be discussed
