### ISSUE TITLE
The closest volunteers to the beneficiary are not displayed correctly V2

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/voluntar-web#78]
Most volunteers displayed don`t live in the proximity of the beneficiary. 
List the volunteers in the closest proximity on top of the page.

**Comment by johnsmithm** [comment]
here should be a map of beneficiary location + all the volunteer closed from the list.
- add two tabs: one for the list, another for the map(or add a button to display a map with volunteers + beneficiary).

**Comment by johnsmithm** [comment]
+ we need an example where the list is not working corectly

**Comment by mihaelataranu7** [comment]
![image](https://user-images.githubusercontent.com/62308267/79730419-7d5dfa80-82f9-11ea-8323-34355adfb11e.png)
![image](https://user-images.githubusercontent.com/62308267/79730589-ba29f180-82f9-11ea-9ada-ec377fe78362.png)

This beneficiary lives on Sciusev 55, which is 6 km away to the first volunteer displayed in the list, but it says 659 km ( issue 1). BTW, all volunteers displayed in the list are shown as 659 km away.
When I open the list of volunteers, filtering centre sector = the same as beneficiary' sector, I see other volunteers name, located much closer to the beneficiary (1-3 km), but that are not displayed in the list "Volunteers nearby Beneficiary" (issue 2).

**Comment by johnsmithm** [comment]
I meant the link, and it is a backend problem, a good idea to have on frontend a map to see how far are the people. Usually the correct address should have chsinau in it, if it is chosen from the options

**Comment by johnsmithm** [comment]
edit the comment has personal information

**Comment by johnsmithm** [comment]
@mihaelataranu7 
adresa nu era scrisa corect, ce duce la coordonate gresite, apoi la lista voluntarilor din apropiere gresiti.
![adresa ok1](https://user-images.githubusercontent.com/10476109/79946769-4ca4cf00-8479-11ea-8c86-ba566e1fadb8.png)
![adresa nu ok](https://user-images.githubusercontent.com/10476109/79946770-4d3d6580-8479-11ea-9ade-9f2f99387390.png)
![adresa ok](https://user-images.githubusercontent.com/10476109/79946773-4d3d6580-8479-11ea-94d7-ed0c7337c41f.png)
