### ISSUE TITLE
Change the beneficiary list: columns displayed and status

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/voluntar-web#82]
- [x] In the beneficiaries” list display only columns: name, phone, sector, status

- [x] for status display a slider with 3 positions: new, in progress, done

- [x] change the status options in the beneficiary form and filter: new, in progress, done

**Comment by valeraf** [comment]
sector  - это что у нас ?
Raion - botanica, centru. etc… ?

for status display a slider with 3 positions: new, in progress, done
это как ? 
в таблице надо слайдер ?

**Comment by valeraf** [comment]
На данный момент оставил Cancelled статус
У нас есть отличия Cancelled by operator VS Cancelled by volunteer?
@mihaelataranu7
