### ISSUE TITLE
Create two comment sections  in the beneficiary form

### ISSUE THREAD

**Issue by mihaelataranu7** [code4moldova/voluntar-web#86]
2 sections for the comments: for a volunteer and for an operator

**Comment by johnsmithm** [comment]
fields name in the db:
- comments: String - field of the comments from the volunteer(read only)
- fixer_comment - comment from the fixer

**Comment by mihaelataranu7** [comment]
@johnsmithm  
fields name in the db:
 fixer_comment  should be operator_comment
Operator comments (the person that talks to the beneficiary)

**Comment by valeraf** [comment]
I'm fine with property key names :)
just wanted to double check who is who :)

@mihaelataranu7 
@johnsmithm

**Comment by valeraf** [comment]
ok i am confused :)

_comments: String - field of the comments from the volunteer(read only)_
Кто добавляет этот комментарий?

@mihaelataranu7 
@johnsmithm

**Comment by valeraf** [comment]
Pushed changes to TEST, 
Check please
and let me know 

@mihaelataranu7
